
spring.datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host}/${db.name}
    username: ${db.username}
    password: ${db.password}

# Date Format
spring.jackson.date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
spring.jackson.serialization.write_dates_as_timestamps: false