
spring.datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host}/${db.name}
    username: ${db.username}
    password: ${db.password}

spring.jackson.date-format: "MM-dd-yyyy HH:mm"
spring.jackson.serialization.write_dates_as_timestamps: false