
spring.datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/briky_local_test?useSSL=false
    url: jdbc:mysql://localhost:3306/briky_local_production?useSSL=false
    username: root
    password: root

#spring.jackson.date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
spring.jackson.date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
spring.jackson.serialization.write_dates_as_timestamps: false

# Logging
logging.level.org.hibernate.SQL: debug